/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "SCLK1_aliases.h"
#include "SCLK1.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "MOSI1_aliases.h"
#include "MOSI1.h"
#include "MISO1_aliases.h"
#include "MISO1.h"
#include "SWITCHES.h"
#include "Clock_1.h"
#include "LEDS.h"
#include "UART.h"
#include "P2_aliases.h"
#include "P2.h"
#include "P1_aliases.h"
#include "P1.h"
#include "P3_aliases.h"
#include "P3.h"
#include "P4_aliases.h"
#include "P4.h"
#include "SS12_aliases.h"
#include "SS12.h"
#include "ControlRegDisp.h"
#include "SS13_aliases.h"
#include "SS13.h"
#include "SS14_aliases.h"
#include "SS14.h"
#include "SS11_aliases.h"
#include "SS11.h"
#include "SPIM_IntClock.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

